export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ALLEVENTS_ROUTE = '/'
export const EVENT_ROUTE = '/event'
export const CREATE_EVENT_ROUTE = '/create'
export const REGISTRATION_EVENTS_ROUTE = '/regmp'